version: '3.8'

services:
  backend:
    image: remmo1/tic-tac-toe-spring:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SOCKET-SERVER_PORT=8080
  
  frontend:
    image: remmo1/tic-tac-toe-react:0.0.1-SNAPSHOT
    ports:
      - "3000:3000"
