version: '3.8'

services:
  backend:
    # image: remmo1/tic-tac-toe-spring:0.0.1-SNAPSHOT
    build:
      context: ./game
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SOCKET-SERVER_PORT=8080
  
  frontend:
    # image: remmo1/tic-tac-toe-react:0.0.1-SNAPSHOT
    build:
      context: ./tic-tac-toe-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_LINK=http://34.207.121.52:8080/
