version: '3.8'

services:
  backend:
    image: remmo1/tic-tac-toe-spring:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8000
      - SOCKET-SERVER_PORT=8080
      - SOCKET-SERVER_HOST=0.0.0.0
  
  frontend:
    image: remmo1/tic-tac-toe-react:0.0.1-SNAPSHOT
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_LINK=http://localhost:8080
