version: '3.8'

services:
  # backend:
  #   # image: remmo1/tic-tac-toe-spring:0.0.1-SNAPSHOT
  #   build:
  #     context: ./game
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SOCKET-SERVER_PORT=8080
  
  # frontend:
  #   # image: remmo1/tic-tac-toe-react:0.0.1-SNAPSHOT
  #   build:
  #     context: ./tic-tac-toe-react
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_LINK=http://34.207.121.52:8080/
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: uzytkownik
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
