version: '3.8'

services:
  backend:
    image: remmo1/tic-tac-toe-spring:0.1.2-SNAPSHOT
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SOCKET-SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/games
      - SPRING_DATASOURCE_USERNAME=uzytkownik
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd!
  
  frontend:
    image: remmo1/tic-tac-toe-react:0.1.2-SNAPSHOT
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_LINK=/
      - REACT_APP_USER_POOL_ID=us-east-1_9LgcvyFtD
      - REACT_APP_CLIENT_ID=243u68h4ne12orqgmh5a8ombvu
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: games
      POSTGRES_USER: uzytkownik
      POSTGRES_PASSWORD: P@ssw0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
